/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Student = IDL.Record({
  'branch' : IDL.Text,
  'semester' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'rollNumber' : IDL.Text,
  'phone' : IDL.Text,
});
export const Teacher = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'employeeId' : IDL.Text,
  'department' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStudent' : IDL.Func([Student], [], []),
  'addTeacher' : IDL.Func([Teacher], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkAddStudents' : IDL.Func([IDL.Vec(Student)], [], []),
  'bulkAddTeachers' : IDL.Func([IDL.Vec(Teacher)], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getStudent' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
  'getTeacher' : IDL.Func([IDL.Text], [IDL.Opt(Teacher)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'listAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Student = IDL.Record({
    'branch' : IDL.Text,
    'semester' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'rollNumber' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Teacher = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'employeeId' : IDL.Text,
    'department' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStudent' : IDL.Func([Student], [], []),
    'addTeacher' : IDL.Func([Teacher], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkAddStudents' : IDL.Func([IDL.Vec(Student)], [], []),
    'bulkAddTeachers' : IDL.Func([IDL.Vec(Teacher)], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getStudent' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
    'getTeacher' : IDL.Func([IDL.Text], [IDL.Opt(Teacher)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'listAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };