/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Student {
  'branch' : string,
  'semester' : string,
  'name' : string,
  'email' : string,
  'rollNumber' : string,
  'phone' : string,
}
export interface Teacher {
  'subject' : string,
  'name' : string,
  'email' : string,
  'employeeId' : string,
  'department' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStudent' : ActorMethod<[Student], undefined>,
  'addTeacher' : ActorMethod<[Teacher], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkAddStudents' : ActorMethod<[Array<Student>], undefined>,
  'bulkAddTeachers' : ActorMethod<[Array<Teacher>], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getStudent' : ActorMethod<[string], [] | [Student]>,
  'getTeacher' : ActorMethod<[string], [] | [Teacher]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllStudents' : ActorMethod<[], Array<Student>>,
  'listAllTeachers' : ActorMethod<[], Array<Teacher>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];